Traceback (most recent call last):
  File "driver_1130.py", line 87, in <module>
    lon_manas=np.loadtxt(path1+"watershed_lon.asc",skiprows=6);lon_manas=np.flipud(lon_manas)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 896, in loadtxt
    fh = iter(open(fname, 'U'))
IOError: [Errno 2] No such file or directory: './data/watershed_lon.asc'
Traceback (most recent call last):
  File "driver_1130.py", line 87, in <module>
    lon_manas=np.loadtxt(path1+"watershed_lon.asc",skiprows=6);lon_manas=np.flipud(lon_manas)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 917, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/_datasource.py", line 260, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/_datasource.py", line 616, in open
    raise IOError("%s not found." % path)
IOError: ./data/watershed_lon.asc not found.
Traceback (most recent call last):
  File "driver_1130.py", line 87, in <module>
    lon_manas=np.loadtxt(path1+"watershed_lon.asc",skiprows=6);lon_manas=np.flipud(lon_manas)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 917, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/_datasource.py", line 260, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/_datasource.py", line 616, in open
    raise IOError("%s not found." % path)
IOError: ./data/watershed_lon.asc not found.
Traceback (most recent call last):
  File "driver_1130.py", line 87, in <module>
    lon_manas=np.loadtxt(path1+"watershed_lon.asc",skiprows=6);lon_manas=np.flipud(lon_manas)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 917, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/_datasource.py", line 260, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/_datasource.py", line 616, in open
    raise IOError("%s not found." % path)
IOError: ./data/watershed_lon.asc not found.
Traceback (most recent call last):
  File "driver_1130.py", line 87, in <module>
    lon_manas=np.loadtxt(path1+"watershed_lon.asc",skiprows=6);lon_manas=np.flipud(lon_manas)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 917, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/_datasource.py", line 260, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/_datasource.py", line 616, in open
    raise IOError("%s not found." % path)
IOError: ./data/watershed_lon.asc not found.
Traceback (most recent call last):
  File "driver_1130.py", line 89, in <module>
    lon_manas=np.loadtxt(path1+"watershed_lon.asc",skiprows=6);lon_manas=np.flipud(lon_manas)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 917, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/_datasource.py", line 260, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/_datasource.py", line 616, in open
    raise IOError("%s not found." % path)
IOError: ./data/watershed_lon.asc not found.
